### ISSUE TITLE
Support for private gcr registries

### ISSUE THREAD

**Issue by awasilyev** [doitintl/kube-secrets-init#22]
Hi
currently it is fails if container image is stored on the private gcr registry with the following error:

```
Error creating: Internal error occurred: failed calling webhook "pods.kube-secrets-init.admission.doit-intl.com": an error on the server ("{\"kind\":\"AdmissionReview\",\"apiVersion\":\"admission.k8s.io/v1beta1\",\"response\":{\"uid\":\"cf21320d-1d33-4fc6-a6f5-65a550ed25ef\",\"allowed\":false,\"status\":{\"metadata\":{},\"status\":\"Failure\",\"message\":\"could not mutate object: failed to mutate pod: : cannot create client for registry: Get \\\"https://gcr.io/v2/\\\": http: non-successful response (status=401 body=\\\"{\\\\\\\"errors\\\\\\\":[{\\\\\\\"code\\\\\\\":\\\\\\\"UNAUTHORIZED\\\\\\\",\\\\\\\"message\\\\\\\":\\\\\\\"Unauthorized access.\\\\\\\"}]}\\\")\"}}}") has prevented the request from succeeding
```

it is impossible to solve this by providing registry credentials - as there is no static password, it should support gcr method of authentication

**Comment by AntonioCayulao** [comment]
Hi @awasilyev 
How do you did to make a work around about this problem? 
Do you also use workload-identity, right? 
Any help that you can do I will really appreciate! 
Greetings!

**Comment by JTarball** [comment]
Any updates on this issue -  I am experiencing the same problem

**Comment by zenyui** [comment]
any updates on this? I'm having the same issue.

**Comment by zenyui** [comment]
I _think_ I found the issue. I'm doing some tests and will post an update.

**Temporary workaround:** set the command and args for your container, even if they are specified in the Dockerfile.
```yaml
containers:
- name: frontend-api
  image: "private-org/some-image:latest"
  command: [ './server' ]
  args: [ 'run' ]
```
@awasilyev @AntonioCayulao @JTarball FYI

**Comment by brtknr** [comment]
> I _think_ I found the issue. I'm doing some tests and will post an update.
> 
> **Temporary workaround:** set the command and args for your container, even if they are specified in the Dockerfile.
> 
> ```yaml
> containers:
> - name: some-container
>   image: 'private-org/some-image:latest'
>   command: [ './server' ]
>   args: [ 'run' ]
> ```
> 
> @awasilyev @AntonioCayulao @JTarball FYI

This did the trick for us but still a bit crap having to do it.

**Comment by zenyui** [comment]
@brtknr yeah, dont love it either, just sharing our hack.

my team forked the repo and will spend some cycles trying to see if we can add logs and sort out why the service account permissions aren't being used. will post an update when we sort it.

**Comment by sagikazarmark** [comment]
Hey folks!

Since the original registry code is based on [Bank Vaults](https://github.com/banzaicloud/bank-vaults) from Banzai Cloud, I think I can offer a little bit of context here.

Let's start with the reason _why_ kube-secrets-init needs registry access in the first place (and why @zenyui 's workaround works): in order to successfully prepend the secrets-init command to the container command (entrypoint), the webhook needs to know what it is. If you specify a command (and args) then the webhook can just mutate those fields, job done. But if not (in which case Kubernetes also falls back to the entrypoint and command in the container image) the webhook needs to look at the image to determine those parameters.

Now, the current code in this repo uses Heroku's "old" docker client that only supports username-password based. Both Bank Vaults and kube-secrets-init used image pull secrets in the pod to try and authenticate against private registries.

Obviously, we also received complaints about this at Banzai Cloud, so we replace this implementation with [another one](https://github.com/banzaicloud/bank-vaults/blob/3bf9a1a1ce91eefa5dc29a08552a505e7a22baf7/pkg/webhook/registry.go#L128) using Google's [go-containerregistry](https://github.com/google/go-containerregistry/blob/main/pkg/authn/k8schain/k8schain.go) library.

In addition to image pull secrets it also takes into account workload/cloud provider identity based registries as well (it supports ECR, GCR and ACR).

Given the registry implementation in kube-secrets-init is basically a 1:1 copy from Bank Vaults, I think it'd be relatively easy to do the same thing again and just copy the updated version using the new library.

(There are some changes, so if you decide to make the change keep out for those. Maybe first just diff the old registry implementation with the one in this library to see the differences first)

Hope this helps! If I get the time I might make the change myself, but I can't say when.

**Comment by zenyui** [comment]
@sagikazarmark my team would be interested in contributing. I'll take a look soon and reach out with questions!

**Comment by sagikazarmark** [comment]
@zenyui Sure, happy to help!

**Comment by brtknr** [comment]
Is there due to be a new release at any point with this fix?
